### ISSUE TITLE
Works only with rails

### ISSUE THREAD

**Issue by alhafoudh** [jsdf/sprockets-coffee-react#4]
How can we get this to use outside rails?

**Comment by jsdf** [comment]
I've added [some instructions for using this gem with only Rack+Sprockets](https://github.com/jsdf/sprockets-coffee-react/blob/master/README.rdoc#how-to-use-with-a-rack-application). Can you give them a go and see if they work for you?

**Comment by alhafoudh** [comment]
Wow, that was quick. I fixed it just by adding:
````
Sprockets.register_engine '.cjsx', Sprockets::CoffeeReactScript
Sprockets.register_engine '.js.cjsx', Sprockets::CoffeeReactScript
````
