### ISSUE TITLE
Allow `.cjsx` without requiring `.coffee.cjsx`

### ISSUE THREAD

**Issue by geoffharcourt** [jsdf/sprockets-coffee-react#6]
This is a totally minor feature request in terms of importance, but would definitely be nice to have.

Currently, you don't have to put an intermediate `.js` in your Coffeescript file names to have those files compile down to JavaScript. It would make for cleaner filenames in Rails projects if you could do the same thing and just call the file `card.cjsx` rather than `card.coffee.cjsx`.

**Comment by martijnrusschen** [comment]
+1

**Comment by jsdf** [comment]
This actually used to work, but doesn't any longer, for some reason. I'll look into it when I have time, but it's a lower priority issue.

**Comment by swrobel** [comment]
Works for me in Rails 4.2.4 with `.js.cjsx` but not just `.cjsx`

**Comment by dbackeus** [comment]
+1
