### ISSUE TITLE
We need documentation on how to implement it with Rails

### ISSUE THREAD

**Issue by sakoh** [jsdf/sprockets-coffee-react#7]
Because I haven't been able to get it to work with Rails yet.

**Comment by jsdf** [comment]
All you should have to do is add "sprockets-coffee-react" to your gemfile and then bundle install. It should Just Work, due to the Rails engine provided by the gem. If it isn't working, perhaps something is going wrong with the Rails integration. What is the exact Rails version you're running?

**Comment by sakoh** [comment]
Rails 4.2.0

**Comment by sakoh** [comment]
I figured it out, you have to put all the js files at the end of the body after `<%= yield %>` instead of in the head.

**Comment by jsdf** [comment]
Are you waiting for document ready before doing your initial render?
