### ISSUE TITLE
Update to coffee-react 4.0.0

### ISSUE THREAD

**Issue by psugihara** [jsdf/sprockets-coffee-react#9]
Would love to have the automatic displayName stuff.

**Comment by swrobel** [comment]
@psugihara I discovered that if you use the `.jsx.cjsx` extension, it will apparently run through the jsx transformer and add displayName

**Comment by jsdf** [comment]
Sprockets-coffee-react doesn't actually use coffee-react, just coffee-react-transform. However, I've updated it to include the JS post-transformations which should have the same effect.
